"""empty message

Revision ID: b4617b98a56b
Revises: b2b2d8315373
Create Date: 2022-02-03 18:25:23.999405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4617b98a56b'
down_revision = 'b2b2d8315373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.execute('UPDATE "public"."user" SET date_created = NOW()')
    op.alter_column('user', 'date_created', nullable=True)
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
